# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/yn38iluz/Documents/alu/workspace/alu/alu.cache/wt [current_project]
set_property parent.project_path /home/yn38iluz/Documents/alu/workspace/alu/alu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib /home/yn38iluz/Documents/alu/alu.vhd
synth_design -top alu -part xc7z020clg484-1
write_checkpoint -noxdef alu.dcp
catch { report_utilization -file alu_utilization_synth.rpt -pb alu_utilization_synth.pb }
